name: Ray Harmon Short Film
favicon: null
layout_spectrum: 0.49849
typography_spectrum: 0.75626
title: Ray Harmon Short Film
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010504'
    - '#f0edcc'
    - '#b0b271'
    - '#7f8547'
    - '#725b4d'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
