name: Ray Harmon Short Film
favicon: null
layout_spectrum: 0.7664488079026341
typography_spectrum: 0.42192493565380573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6764799214433879
  lightness: 0.43669273518025875
  saturation: 0.8317113998346031
  rhythmicContrast: 0.5961279468610883
purpose: []
